export const List = [
    {
        "birthDate": "14.07.1948",
        "gender": "FEMALE",
        "_event": null,
        "deactivateEvent": null,
        "branch": 1202,
        "certSeries": "II-ВП",
        "certNumber": "340652",
        "certDate": "13.03.1986",
        "taskSubstate": null,
        "taskSubmessage": null,
        "active": true,
        "action": "VIEW",
        "stages": "[[OPEN, BIND, NAME, LAST]]",
        "memberNum": 4
      },
      {
        "id": 7463433,
        "traversal": "DAUGHTER",
        "certTraversal": "DAUGHTER",
        "pnfl": null,
        "surname": "RUSTAMOVA",
        "name": "MALIKA",
        "patronym": "BAXODIR QIZI",
        "birthDate": "11.09.2019",
        "gender": "FEMALE",
        "_event": null,
        "deactivateEvent": null,
        "branch": 1202,
        "certSeries": "I-SR",
        "certNumber": "0323629",
        "certDate": "13.09.2019",
        "taskSubstate": null,
        "taskSubmessage": null,
        "active": true,
        "action": "VIEW",
        "stages": "[[OPEN, BIND, NAME, LAST]]",
        "memberNum": 0
      },
      {
        "id": 7463434,
        "traversal": "SELF",
        "certTraversal": "SELF",
        "pnfl": "30903862890037",
        "surname": "NADIROV",
        "name": "BAXODIR",
        "patronym": "RUSTAMOVICH",
        "birthDate": "09.03.1986",
        "gender": "MALE",
        "_event": null,
        "deactivateEvent": null,
        "branch": 1202,
        "certSeries": "I-SR",
        "certNumber": "0083362",
        "certDate": "05.12.2015",
        "taskSubstate": null,
        "taskSubmessage": null,
        "active": true,
        "action": "HIDE",
        "stages": "[[OPEN, LAST]]",
        "memberNum": 2
      },
      {
        "id": 7463435,
        "traversal": "FATHER",
        "certTraversal": "SELF",
        "pnfl": null,
        "surname": "НАДИРОВ",
        "name": "РУСТАМ",
        "patronym": null,
        "birthDate": "01.05.1944",
        "gender": "MALE",
        "_event": null,
        "deactivateEvent": null,
        "branch": 1202,
        "certSeries": "II-ВП",
        "certNumber": "340652",
        "certDate": "13.03.1986",
        "taskSubstate": null,
        "taskSubmessage": null,
        "active": true,
        "action": "VIEW",
        "stages": "[[OPEN, BIND, NAME, LAST]]",
        "memberNum": 6
      },
      {
        "id": 7463436,
        "traversal": "SELF",
        "certTraversal": "SELF",
        "pnfl": "30903862890037",
        "surname": "НАДИРОВ",
        "name": "БАХОДИР",
        "patronym": "РУСТАМОВИЧ",
        "birthDate": "09.03.1986",
        "gender": "MALE",
        "_event": null,
        "deactivateEvent": null,
        "branch": 1202,
        "certSeries": "II-ВП",
        "certNumber": "340652",
        "certDate": "13.03.1986",
        "taskSubstate": null,
        "taskSubmessage": null,
        "active": true,
        "action": "VIEW",
        "stages": "[[OPEN, BIND, PRESERVE]]",
        "memberNum": 2
      }
    ]
    
